source "https://rubygems.org/"

gem 'json-ld', :git => "git://github.com/ruby-rdf/json-ld.git", :require => 'json/ld'
gem 'linkeddata'
gem 'rack'
gem 'rdf-rdfa', :git => "git://github.com/ruby-rdf/rdf-rdfa.git", :require => 'rdf/rdfa'
gem 'sparql'
gem 'thin'
