class WebResource
  module HTML
    Icons = {
      'uri' => :id,
      Comments => :comments,
      Container => :dir,
      Content => :pencil,
      DC+'identifier' => :barcode,
      DC+'cache' => :chain,
      DC+'hasFormat' => :file,
      DC+'link' => :chain,
      DC+'List' => :list,
      DC+'Video' => :video,
      Date => :date,
      Image => :img,
      Label => :tag,
      Mtime => :time,
      RSS+'comments' => :comments,
      SIOC+'BlogPost' => :pencil,
      SIOC+'ChatLog' => :comments,
      SIOC+'Discussion' => :comments,
      SIOC+'Feed' => :feed,
      SIOC+'InstantMessage' => :comment,
      SIOC+'MailMessage' => :envelope,
      SIOC+'MicroblogPost' => :newspaper,
      SIOC+'Post' => :newspaper,
      SIOC+'SourceCode' => :code,
      SIOC+'reply_of' => :reply,
      SIOC+'Thread' => :openenvelope,
      SIOC+'Tweet' => :bird,
      SIOC+'Usergroup' => :group,
      SIOC+'WikiArticle' => :pencil,
      SIOC+'has_creator' => :user,
      SIOC+'has_discussion' => :comments,
      SIOC+'user_agent' => :mailer,
      Schema+'Person' => :user,
      Schema+'location' => :location,
      Size => :size,
      Sound => :speaker,
      Stat+'Archive' => :archive,
      Stat+'DataFile' => :tree,
      Stat+'File' => :file,
      Stat+'HTMLFile' => :html,
      Stat+'MarkdownFile' => :markup,
      Stat+'TextFile' => :textfile,
      Stat+'WordDocument' => :word,
      Stat+'container' => :dir,
      Stat+'contains' => :dir,
      Stat+'height' => :height,
      Stat+'width' => :width,
      Title => :title,
      To => :userB,
      Type => :type,
      W3+'2000/01/rdf-schema#Resource' => :node,
    }
  end
end
