#!/usr/bin/env ruby
require 'open3'
Open3.popen3("tail -f log/access.log") do |stdin, stdout, stderr, thread|
  while line = stdout.gets do
    t = line.split ' '
    status,method,addr,action,mime = [t[3],t[5],t[6],t[8],t[9]]
    blocked = false
    statusColor = case status
                  when /304/
                    '37' # white
                  when /(40[03]|500|ABORT|DENIED)/
                    blocked = true
                    '31' # red
                  when /200/
                    '32' # green
                  else
                    '30' # gray
                  end
    destColor = if blocked
                  '31' # red
                elsif method == 'CONNECT'
                  '32' # green
                else
                  case action
                  when /(ORIGINAL|DIRECT)/
                    '32' # green
                  else
                    '37' # white
                  end
                end

    puts "\e[7m" + method + "\e[" + statusColor + ";1m " + status + "\e[" + destColor + ";1m " + addr + "\e[0m " + "#{action} #{mime}"
  end
end
