#!/usr/bin/env ruby
exit 0 if ARGV.empty?
require 'ww'
begin
  uri = R[ARGV[0]]
  # eat querystring
  r = R[uri.to_s.sub(/\?#{uri.query}$/,'')]
  r.setEnv({ 'QUERY_STRING' => uri.query||'',
             'REQUEST_PATH' => r.justPath.to_s,
             'REQUEST_URI' => uri.justPath.to_s,
             'SERVER_NAME' => r.host||'localhost',
             :Response => {}, :Links => {},
           }.extend Th)

  # do
  puts r.send *ARGV[1..-1]

end
