#!/bin/sh
while true; do
date
getmail
rsync -avz ~/.mail p:
R `date +/%Y/%m/%d/` HEAD # index, optional - visiting messages via /today or /2016?set=depth "inbox" will index on-demand 
sleep 1600
done
