#!/bin/sh
# start session and HTTP daemon
tmux new-session -s web -d -c ~/web
tmux send-keys -t web:0 'unicorn -p 8000 -o localhost .conf/rack.ru' C-m
su -c './routes'

# in
tmux new-window -t web:1 -d mitmdump -p 8888 -m reverse:http://localhost:8000 --set keep_host_header=true
# out
tmux new-window -t web:2 -d mitmdump

# state synchronization
tmux new-window -t web:3 -d
tmux send-keys -t web:3 "watch -n 288 rsync -av u@node:web/`date +%Y/%m/%d` ~/web/`date +%Y/%m`" C-m

# user input
tmux attach-session -t web
