#!/bin/sh

## package distributions

# https://www.alpinelinux.org/
which apk && apk add alpine-sdk graphicsmagick ruby ruby-dev python python3-dev py3-cffi py3-pip openssl-dev rsync libxslt-dev tmux squid

# https://www.debian.org/
which apt-add-repository && apt-get install graphicsmagick git ruby ruby-dev grep file pkg-config libssl-dev libxslt-dev tmux squid make rsync libffi-dev python-dev python3-pip

# https://www.archlinux.org/
which pacman &&  pacman -S graphicsmagick git base-devel ruby ruby-rdoc python-pip pkg-config tmux squid make rsync

# https://termux.com/
which pkg && pkg install graphicsmagick git ruby ruby-dev grep file findutils pkg-config libxslt-dev clang tmux squid make rsync libffi-dev python python-dev libcrypt-dev openssl-tool openssl-dev

## languages

# https://www.python.org/
pip install --upgrade pygments

# https://www.ruby-lang.org/
cd ruby
ruby install
gem install bundler
bundle install

## init file layout
mkdir ~/web
cd ~/web
ln -s ../src/pw/config/ .conf
