#!/bin/sh

# system package dependencies. detect Termux and Debian via extant package-tools in $PATH. TODO Gentoo etc.
which pkg && pkg install graphicsmagick git ruby ruby-dev grep file findutils pkg-config libxslt-dev clang tmux make rsync libffi-dev python python-dev libcrypt-dev openssl-tool openssl-dev
which apt-add-repository && apt-get install graphicsmagick git ruby ruby-dev grep file findutils pkg-config libssl-dev libxslt-dev clang tmux make rsync libffi-dev python-dev python3-pip
#which emerge &&

# Ruby library dependencies
gem install bundler
cd ruby
bundle install
ruby install # link source-dir into Ruby library-dir
#TODO use env-vars and remove this step since some distros have weird frankenperms thing where user gems try to install ito system dirs and ask for root and this won't be user-writeable. works as root and on Termux and user-sandboxed ruby-library configged distros, increasingly common, as is

# Python library dependencies
pip3 install --upgrade pip
pip3 install --upgrade mitmproxy pygments

# certificate
cert=$(realpath ~/.mitmproxy/mitmproxy-ca-cert.pem)
hash=$(openssl x509 -inform PEM -subject_hash_old -in $cert -noout)
su -c "cp $cert /system/etc/security/cacerts/$hash.0"
