#!/bin/sh
# for now drop QUIC/UDP until we figure out how to handle it. seems wishlisted for existing proxies circa 2018
iptables  -A OUTPUT -p udp -m owner ! --uid-owner `id -u` --dport  80 -j DROP
ip6tables -A OUTPUT -p udp -m owner ! --uid-owner `id -u` --dport  80 -j DROP
iptables  -A OUTPUT -p udp -m owner ! --uid-owner `id -u` --dport 443 -j DROP
ip6tables -A OUTPUT -p udp -m owner ! --uid-owner `id -u` --dport 443 -j DROP

# route TCP traffic to incoming and outgoing proxy pair
iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner `id -u` --dport  80 -j REDIRECT --to-ports 8000
ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner `id -u` --dport  80 -j REDIRECT --to-ports 8000
iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner `id -u` --dport 443 -j REDIRECT --to-ports 8888
ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner `id -u` --dport 443 -j REDIRECT --to-ports 8888
