#!/bin/sh
esc=$(printf '\033')
tail -f log/access.log | grep -v '\(DENIED\|/50[03] \)' |
    sed -e "s|\([^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\(https*://[^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*|$esc[34m\1 $esc[35m\2$esc[0m $esc[36;1;7m\3$esc[0m \4 $esc[2m\5$esc[0m $esc[1m\6$esc[0m|"
