#!/bin/sh
esc=$(printf '\033')
tail -f log/access.log | sed -e "s/\([^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*\)[[:space:]]*\(https*:\/\/[^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\(DIRECT\|ORIGINAL\)[^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*/\1 $esc[0m $esc[32;1;7m\2$esc[0m \3 $esc[2m\4$esc[0m $esc[1m\6$esc[0m/"
