#!/bin/sh
esc=$(printf '\033')
tail -f log/access.log | grep '\(DENIED\|/50[03] \)' |
    sed -e "s|[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*https*://\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*|\1 $esc[7m\2$esc[0m $esc[7m$esc[31;1m\3$esc[0m \4 $esc[2m\5$esc[0m $esc[1m\6$esc[0m|"
