#!/bin/sh
#uid=$(id -u)
uid=10079
app_path=$(realpath ~/src/pw)
os_path=/data/mnt/alpine

## session
tmux new-session -s web -d -c ~/web

## daemons
tmux send-keys -t web:0 'unicorn -N -p 8000 .conf/rack.ru' C-m
su -c "sh $app_path/sh/services $app_path"

## forward proxy
squid -f $app_path/config/squid.conf
tmux new-window -t web:1 -d $app_path/sh/proxylog

## reverse proxy
tmux new-window -t web:2 -d
tmux send-keys -t web:2 "su -c 'chroot $os_path /bin/su -c \"mitmdump -p 8080 -m reverse:http://127.0.0.1:8000 --set keep_host_header=true\" - web'" C-m

## TCP routes
# agent -> forward proxy (3128)      -> remote daemon (443)
# agent -> original HTTP  dest (80)  -> local daemon  (8000)
# agent -> original HTTPS dest (443) -> reverse proxy (8080) -> local daemon (8000)
su -c "sh $app_path/sh/routes $uid"

## database
tmux new-window -t web:3 -d
tmux send-keys -t web:3 "watch -n 288 rsync -av $DATAPEER:web/`date +%Y/%m/%d` ~/web/`date +%Y/%m`" C-m

## user control
tmux attach-session -t web
