#!/bin/sh
# some shell and sed implementations aren't keen on spaces and esc-sequences in commandlines and char-class specifications
# this ver works for me using [:space:] in lieu of ' ' and putting esc-char in a variable. if escaping experts have another solution working across bionic/musl/glibc coreutils & busybox renditions of sed i'm ears
esc=$(printf '\033')

tail -f $PREFIX/var/logs/access.log | \
    grep -v TCP_DENIED | \
    sed -e "s|\([^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*[^[:space:]]*[[:space:]]*\)\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\(https*://[^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*\([^[:space:]]*\)[[:space:]]*|\1$esc[32;1m\2 $esc[30;7m\3 $esc[36;1m\4$esc[0m $esc[7m\5$esc[0m $esc[2m\6$esc[0m $esc[1m\7$esc[0m|"
