#!/bin/sh
echo

# output proxy domains in comma-seperated format
cat ~/src/pw/config/API.domains ~/src/pw/config/track.domains |
    tr "\n" "," | sed -e 's/.$//' # remove final trailing-comma

# paste output in "bypass proxy for:" box or no_proxy env-var, or use browse script which does the latter for you

# confusingly "No/bypassed Proxy" as in no forward-proxy, but instead the reverse proxy to local daemon

echo;echo
