#!/bin/sh
#uid=$(id -u)
uid=10079 # remove alpine chroot when mitmproxy is fixed
app_path=$(realpath ~/src/pw)
os_path=/data/mnt/alpine

## session
tmux new-session -s web -d -c ~/web

## daemons
# local daemon
tmux send-keys -t web:0 'unicorn -N -p 8000 .conf/rack.ru' C-m
# open ports
su -c "sh $app_path/sh/services $app_path"

## forward proxy to net
squid -f $app_path/config/squid.conf
# tail proxy log
#tmux new-window -t web:1 -d $app_path/sh/proxylog
# tail proxy log on gateway
tmux new-window -t web:1 -d ssh -p 8022 192.168.43.1 ~/src/pw/sh/proxylog

## reverse proxy to daemon
tmux new-window -t web:2 -d
tmux send-keys -t web:2 "su -c 'chroot $os_path /bin/su -c \"mitmdump -p 8080 -m reverse:http://127.0.0.1:8000 --set keep_host_header=true\" - web'" C-m

## TCP routes
# OUT to net
# agent -> forward proxy (3128) -> HTTPS (443)
# IN to daemon
# agent -> HTTP (80) -> daemon (8000)
# agent -> HTTPS (443) -> reverse proxy (8080) -> daemon (8000)
su -c "sh $app_path/sh/routes $uid"

## database
tmux new-window -t web:3 -d
# sync day-dir
tmux send-keys -t web:3 "watch -n 288 rsync -av $DATAPEER:web/`date +%Y/%m/%d` ~/web/`date +%Y/%m`" C-m
# sync month-dir
tmux send-keys -t web:3 "watch -n 28888 rsync -av $DATAPEER:web/`date +%Y/%m` ~/web/`date +%Y`" C-m

## user input
tmux attach-session -t web
