#!/bin/sh
app_path=$(realpath ~/src/pw)
uid=$(id -u)
# session
tmux new-session -s web -d -c ~/web
# routes
su -c "sh $app_path/sh/services $app_path"
su -c "sh $app_path/sh/routes $uid"
# daemon
tmux send-keys -t web:0 'unicorn -N -p 8000 .conf/rack.ru' C-m
# proxy
squid -f $app_path/config/squid.conf
# tail logs
tmux new-window -t web:1 -d $app_path/sh/proxylog
tmux new-window -t web:2 -d ssh -p 8022 192.168.43.1 ~/src/pw/sh/proxylog
# data synchronization
tmux new-window -t web:3 -d
tmux send-keys -t web:3 "watch -n 28888 rsync -av $DATAPEER:web/`date +%Y/%m` ~/web/`date +%Y`" C-m
# user controls
tmux attach-session -t web
