#!/system/bin/sh

# (UDP) TODO find proxy for QUIC and other newfangled protocols
iptables  -A OUTPUT -p udp -m owner ! --uid-owner $1 --dport  80 -j DROP
ip6tables -A OUTPUT -p udp -m owner ! --uid-owner $1 --dport  80 -j DROP
iptables  -A OUTPUT -p udp -m owner ! --uid-owner $1 --dport 443 -j DROP
ip6tables -A OUTPUT -p udp -m owner ! --uid-owner $1 --dport 443 -j DROP

# (TCP) route HTTPS traffic to proxy
iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport 443 -j REDIRECT --to-ports 8888
ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport 443 -j REDIRECT --to-ports 8888
