#!/bin/sh
UID=10006
# for now drop QUIC/UDP until proxy support improves
iptables  -A OUTPUT -p udp -m owner ! --uid-owner $UID --dport  80 -j DROP
ip6tables -A OUTPUT -p udp -m owner ! --uid-owner $UID --dport  80 -j DROP
iptables  -A OUTPUT -p udp -m owner ! --uid-owner $UID --dport 443 -j DROP
ip6tables -A OUTPUT -p udp -m owner ! --uid-owner $UID --dport 443 -j DROP

# route TCP traffic to proxy high-ports
iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $UID --dport  80 -j REDIRECT --to-ports 8000
ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $UID --dport  80 -j REDIRECT --to-ports 8000
iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $UID --dport 443 -j REDIRECT --to-ports 8888
ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $UID --dport 443 -j REDIRECT --to-ports 8888
