#!/system/bin/sh
# route HTTP traffic to proxy
iptables  -A OUTPUT -p udp -m owner ! --uid-owner $1 --dport  80 -j DROP
ip6tables -A OUTPUT -p udp -m owner ! --uid-owner $1 --dport  80 -j DROP
iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport  80 -j REDIRECT --to-ports 8000
ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport  80 -j REDIRECT --to-ports 8000
