#!/system/bin/sh
# route HTTPS traffic to proxy
iptables  -A OUTPUT -p udp -m owner ! --uid-owner $1 --dport 443 -j DROP
ip6tables -A OUTPUT -p udp -m owner ! --uid-owner $1 --dport 443 -j DROP
#iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport 443 -j REDIRECT --to-ports 8888
#ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport 443 -j REDIRECT --to-ports 8888
