#!/bin/sh

iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport  80 -j REDIRECT --to-ports 8000 # ipv4 HTTP to daemon on high-port
ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport  80 -j REDIRECT --to-ports 8000 # ipv6 HTTP to daemon on high-port
iptables  -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport 443 -j REDIRECT --to-ports 8080 # ipv4 HTTPS to reverse-proxy on high-port
ip6tables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner $1 --dport 443 -j REDIRECT --to-ports 8080 # ipv6 HTTPS to reverse-proxy on high-port
