#!/system/bin/sh
sh=$1/sh
open_port=$(realpath $sh/open_port)
open_TCP=$(realpath  $sh/open_TCP)
open_UDP=$(realpath  $sh/open_UDP)

$open_TCP    22 # SSH
$open_TCP    43 # WHOIS
$open_port   53 # DNS
$open_port   67 # DHCP
$open_port   68 # DHCP
$open_TCP    80 # HTTP
$open_TCP   443 # HTTPS
$open_port 6789 # IRC
$open_port 8000 # HTTP
$open_TCP  8022 # SSH
$open_port 8080 #     forward-proxy HTTPS
$open_port 8081 # transparent-proxy HTTPS
$open_UDP 60001 # Mosh
$open_UDP 60002
$open_UDP 60003
