#!/bin/sh
sh $1/open_TCP    22 # SSH
sh $1/open_TCP    43 # WHOIS
sh $1/open_port   53 # DNS
sh $1/open_port   67 # DHCP
sh $1/open_port   68 # DHCP
sh $1/open_TCP    80 # HTTP
sh $1/open_TCP   443 # HTTPS
sh $1/open_port 6789 # IRC
sh $1/open_port 8000 # HTTP
sh $1/open_TCP  8022 # SSH
sh $1/open_port 8080 # HTTPS
sh $1/open_UDP 60001 # Mosh
sh $1/open_UDP 60002
sh $1/open_UDP 60003
