#!/bin/sh
# author's configuration. adjust to taste
# start proxy operation
export https_proxy=https://localhost:8080
export  http_proxy=http://localhost:8080
mitmdump -p 8080 &
# send out of bound requests to penalty box
export no_proxy=localhost,*.myfonts.net,*.ytimg.com,*.eyeota.net,*.quora.com,*.quoracdn.net,*.vox-cdn.com,*.voxmedia.com,*.amazonaws.com,*.adsrvr.org,*.spot.im,*.kargo.com,*.facebook.com,*.cedexis-radar.net,*.twitter.com,*.linkedin.com,*.cloudfront.net,*.yahoo.com,*.facebook.net,*.amazon.com,*.google-analytics.com,*.cloudflare.com,*.doubleclick.net,*.google.com,*.googleadservices.com,*.googleapis.com,*.gstatic.com,*.typography.com,*.sstatic.net,*.bootstrapcdn.com
su -c 'iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 10095 --dport 443 -j REDIRECT --to-ports 8888' # TODO insert uid dynamically
mitmdump -p 443 -m reverse:http://localhost:8000 --set keep_host_header=true &
mitmdump -p 8888 -m reverse:http://localhost:8000 --set keep_host_header=true &
# start local daemon
cd ~/web
unicorn -p 8000 -o localhost .conf/rack.ru &
# start browser
chromium $@
