#!/bin/sh
https_proxy=https://localhost:8080 http_proxy=http://localhost:8080 no_proxy=localhost,*.facebook.com,*.twitter.com,*.cloudfront.net,*.yahoo.com,*.facebook.net,*.google.com,*.googleapis.com,*.amazon.com,*.cloudflare.com chromium $@
