#!/bin/sh
tmux new-session -s web -d
tmux new-window -t web:1 -c ~/web unicorn -p 8000 -o localhost .conf/rack.ru
tmux new-window -t web:2 mitmdump -p 8888 -m reverse:http://localhost:8000 --set keep_host_header=true
tmux new-window -t web:3 mitmdump -m upstream:http://m:8080
tmux new-window -t web:4 iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 10095 --dport  80 -j REDIRECT --to-ports 8000
tmux new-window -t web:5 iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 10095 --dport 443 -j REDIRECT --to-ports 8888
