#!/bin/sh
su -c 'iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 10095 --dport  80 -j REDIRECT --to-ports 8000'
su -c 'iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 10095 --dport 443 -j REDIRECT --to-ports 8888'
tmux new-session -s web -d mitmdump
tmux new-window -t web:1 mitmdump -p 8888 -m reverse:http://localhost:8000 --set keep_host_header=true
tmux new-window -t web:2 -c ~/web unicorn -p 8000 -o localhost .conf/rack.ru
tmux attach-session -t web
