#!/bin/sh
cd ~/web
export https_proxy=https://localhost:8080
export http_proxy=http://localhost:8080

# outbound proxy
mitmdump &
# reverse proxy
mitmdump -p 8888 -m reverse:http://localhost:8000 --set keep_host_header=true &
su -c 'iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 10095 --dport 443 -j REDIRECT --to-ports 8888'

# daemon
unicorn -p 8000 -o localhost .conf/rack.ru &
su -c 'iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 10095 --dport  80 -j REDIRECT --to-ports 8000'
